import { useCallback, useEffect, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import {
  CalendarX2,
  AlertTriangle,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/portal/empty-state";
import { CommentPopover } from "./comment-popover-lazy";
import { ScheduleEditFrameDialog } from "./schedule-edit-frame-dialog-lazy";
import { SessionMemoDot } from "./schedule/session-memo-dot";
import {
  SessionMemoPopover,
  type SessionMemoPopoverHandle,
} from "./session-memo-popover-lazy";
import { PastSessionRemoveButton } from "./schedule/past-session-remove-button";
import {
  useRealtimeAllScheduleMemos,
  type ScheduleSessionMemo,
} from "@/lib/schedule-memos-client";
import {
  getJapaneseHolidayName,
  isJapaneseHoliday,
} from "@/lib/japanese-holidays";
import { Legend } from "@/components/portal/schedule/legend";
import { SessionActionIcons } from "@/components/portal/schedule/session-action-icons";
import {
  describeAttendanceTimes,
  formatAttendanceTimesHint,
} from "@/lib/schedule/attendance-times";
import {
  ATT_TONE,
  ATT_TONE_FALLBACK,
} from "@/lib/schedule/attendance-ui";
import { DECISION_BADGE_CLASS } from "@/lib/schedule/status-ui";
import {
  buildEditUrl,
  groupCommentsByAuthor,
  lookupVideoLinks,
  splitSessions,
} from "@/lib/schedule/session-utils";
import type { JapaneseHolidaysMap } from "@/lib/japanese-holidays";
import type {
  ScheduleAttendanceOptions,
  ScheduleComment,
  ScheduleFetchResult,
  ScheduleSession,
  ScheduleUser,
} from "@/lib/schedule/next-session";
import type { ScheduleSourceMode } from "@/lib/schedule/source-mode";
import type { SessionLogEntry } from "@/lib/schedule/session-logs";
import type { SessionVideoLink } from "@/lib/server/session-video-link";
// C-2 (2026-07-12): native 系は lazy re-export 経由。全 render 箇所が
// mode==="native" ガード下なので sync モードでは chunk ごとロードされない。
import {
  AutoGeneratedBadge,
  NativeAttendancePopover,
  NativeFflogsLinkPopover,
  NativeMemberCommentPopover,
  SessionDiscordNotifyButton,
  SessionStatusToggle,
  SessionTimeEditPopover,
} from "./native-schedule/lazy";

// Stable reference for the realtime hook's initial param — `[]` inline
// would be a fresh array on every render and trip the hook's
// "initial-changed" guard, clobbering fetched memos with empty.
const EMPTY_MEMOS: ScheduleSessionMemo[] = [];

// Default `videoLinks` prop — same stability concern as above.
const EMPTY_VIDEO_LINKS: SessionVideoLink[] = [];

// Default `sessionLogs` prop — array form (TODO #64).
const EMPTY_SESSION_LOGS: SessionLogEntry[] = [];

// SessionRow の `slots` 既定値 (= 1.9.27 の全枠確保と同じ挙動)。表側から
// `reserveSlotsFor()` の結果を渡さない呼び出し元の後方互換用。
const DEFAULT_ROW_SLOTS = { video: true, logs: true, memo: true } as const;

// 日程セルで日付 / 時刻の右に続く chip + アイコン群のクラス。
// `gap-1` のままだと時刻との間隔が日付↔時刻と同じ 4px で、アイコンが時刻の
// 一部のように見える (ユーザー指摘 2026-08-05「時間によりすぎる」)。
// `mx-auto` で列の余り幅を左右に等分し、アイコンの左右の空白が同じ程度に
// 見えるようにする (右端寄せだと今度は確定列側に張り付いて見える)。余りが
// 無い行では `pl-2` ぶんだけ時刻から離れる。
const ICON_GROUP_CLASS = "mx-auto flex items-center gap-1 pl-2";

type Props = {
  result: ScheduleFetchResult;
  /** Maximum sessions to render. Defaults to all upcoming + a small past buffer. */
  limit?: number;
  /**
   * When true, render the FULL detailed past-sessions table at the
   * bottom (with participant columns + time-of-day). The simple
   * date-only strip lives in a separate component (SchedulePastSimple)
   * inserted between the next-session card and the upcoming table.
   */
  showDetailedPast?: boolean;
  /** Source schedule URL — used to derive the per-user edit URL on hover/click. */
  scheduleUrl?: string | null;
  /**
   * Pre-fetched Japanese-holiday map (date → holiday name) passed down
   * from the server page. Used to color holiday rows red and surface
   * the holiday name in the date-cell tooltip. When undefined, the
   * synchronous hardcoded fallback is used.
   */
  holidays?: JapaneseHolidaysMap;
  /**
   * Pre-built `YYYY-MM-DD` → matching-video-link map. When a past
   * session has an entry, its date cell becomes a Link to that
   * video; otherwise the cell renders as plain text.
   */
  sessionVideoLinks?: Record<string, SessionVideoLink[]>;
  /**
   * Pre-built `rawDate` → FFLogs URL entries for past sessions, sourced
   * from `schedule_past_session_logs`. Lets the UI show a Logs icon
   * (or a multi-item dropdown) next to a date even when there's no
   * matching video. TODO #64 (2.1, 2026-05-02 part5): array form.
   */
  sessionLogsByDate?: Record<string, SessionLogEntry[]>;
  /**
   * True if the group has at least one Ultimate cleared. Drives the
   * legend label MEMBERS → LEGENDS swap (1.9.16). Default false.
   */
  hasUltimateClear?: boolean;
  /**
   * 運用ルール / 注意事項のローカル override (Supabase
   * `app_settings.schedule_top_text_override`)。設定済みなら scraped
   * `result.data.topText` より優先表示。Legend popup 内の「編集」ボタンで
   * 上書き可能。
   */
  topTextOverride?: string | null;
  /** TODO #11: server prefetch した memos (rawDate → memos[]) */
  initialMemosByDate?: Record<string, import("@/lib/schedule-memos-client").ScheduleSessionMemo[]>;
  /**
   * TODO #2 phase 2-B: スケジュールソースモード。
   * `"native"` のとき確定列の admin 用 status toggle / 本人 cell の出欠 popover を mount する。
   * default = `"sync"` (既存 character-sheets 経路、native UI 一切無効)。
   */
  mode?: ScheduleSourceMode;
  /**
   * TODO #2 phase 2-B: 認証済 Discord メンバーの ID。
   * native mode の出欠 cell で `currentDiscordId === u.userId` を満たす行のみ
   * `<NativeAttendancePopover>` で render。sync mode では参照しない。
   */
  currentDiscordId?: string | null;
  /**
   * TODO #2 phase 2-B: admin role 持ちか。
   * native mode の確定列で `<SessionStatusToggle>` を表示するかの判定に使う。
   */
  isAdmin?: boolean;
};

export function ScheduleList({
  result,
  limit,
  showDetailedPast = false,
  scheduleUrl,
  holidays,
  sessionVideoLinks,
  sessionLogsByDate,
  hasUltimateClear = false,
  topTextOverride = null,
  initialMemosByDate = {},
  mode = "sync",
  currentDiscordId = null,
  isAdmin = false,
}: Props) {
  // TODO #11 phase 7: 全 memo を 1 channel で監視し、各 SessionRow には
  // 該当 rawDate の slice + refetchAll を props で配る (旧: 各行が個別
  // subscribe → N リスナー × N refetch の問題)。
  const { memosByDate, refetchAll: refetchMemos } =
    useRealtimeAllScheduleMemos(initialMemosByDate);

  // 1.9.13: replace `target="_blank"` external nav with an in-portal
  // iframe overlay. Tapping a username header or per-session attendance
  // cell now sets `editTarget`, which mounts the dialog. State lives at
  // the top level so a single dialog instance is reused across rows.
  //
  // 2.1+ (TODO #44): per-date 確定セルクリックは `targetRowIndex` も
  // 一緒に渡す。dialog 側で URL に `#row_N` hash を付けて character-sheets
  // を該当行までネイティブ jump させる (旧 heuristic translateY 廃止)。
  const [editTarget, setEditTarget] = useState<{
    url: string;
    title: string;
    targetRowIndex: number | null;
  } | null>(null);
  // TODO #53 (2.1, 2026-04-30 part3): base-ui Dialog の scroll lock 解除と
  // FloatingFocusManager の returnFocus が iframe / 高頻度 re-render と組み
  // 合わさるとダイアログ閉じた後にスクロール位置が頭に戻ったり、scroll
  // が一時的に効きにくく見える事象があった。開く瞬間の `window.scrollY`
  // を保存し、閉じた後に rAF 2 回 (= base-ui の `setTimeout(0)` cleanup +
  // exit animation を待つ) してから差分があれば復元する。
  const savedScrollYRef = useRef<number | null>(null);
  const openEditFrame = useCallback(
    (url: string, title: string, targetRowIndex: number | null = null) => {
      if (typeof window !== "undefined") {
        savedScrollYRef.current = window.scrollY;
      }
      setEditTarget({ url, title, targetRowIndex });
    },
    [],
  );
  // editTarget が null に戻ったタイミングで scrollY を復元。差分が小さい
  // (= base-ui が正しく復元できている) 場合は no-op。差分があるときだけ
  // 上書き。`behavior: 'instant'` (= "auto") にして animation を挟まない。
  useEffect(() => {
    if (editTarget !== null) return;
    const saved = savedScrollYRef.current;
    if (saved === null) return;
    savedScrollYRef.current = null;
    let raf1 = 0;
    let raf2 = 0;
    raf1 = requestAnimationFrame(() => {
      raf2 = requestAnimationFrame(() => {
        if (Math.abs(window.scrollY - saved) > 4) {
          window.scrollTo({ top: saved, left: 0, behavior: "instant" });
        }
      });
    });
    return () => {
      if (raf1) cancelAnimationFrame(raf1);
      if (raf2) cancelAnimationFrame(raf2);
    };
  }, [editTarget]);

  // 1.9.28: refresh button next to the legend lets the user pull the
  // latest schedule data on demand (no need to reload the page).
  // useTransition gives the spinner a `pending` flag so the button can
  // show a loader while server-side data is being re-fetched.
  const router = useRouter();
  const [refreshing, startRefresh] = useTransition();
  const refreshSchedule = useCallback(() => {
    startRefresh(() => {
      router.refresh();
    });
  }, [router]);

  // 2.1 (2026-04-29): 詳細過去日程の 2 ヶ月以上前は初期非表示。
  // Past リストは年月が経つほど縦に長くなるが、最近の数試合分しか
  // 普段は参照しないので、デフォルトでは直近 2 ヶ月までを表示し、
  // それ以前は折り畳む。展開ボタンで切り替え可能 (state はここに置
  // いてマウント期間中保持)。
  const [showOlderPast, setShowOlderPast] = useState(false);
  // 2.1 (2026-04-29) hot-fix v2: トグル時にユーザの「視点」(= window.scrollY)
  // を保つ。前バージョン (PR #8) はボタンの rect.top を保つ実装にしていたが、
  // 展開時はボタンが下へ移動するためページが下方向に大量スクロールしてしまい、
  // ユーザが見ていた行が画面外に追い出される事象があった (例: 2/28 で押す
  // と最古の 2/9 まで一気に飛ぶ)。
  //
  // 正しい挙動: 展開しても、ユーザが見ている絶対位置 (= recentPast の中の
  // どこか) はそのまま。展開行 (olderPast) は画面外下方に挿入され、ユーザは
  // スクロールダウンで読みに行く。畳み時も同じく絶対位置を保つ (ドキュメント
  // 高が縮むので、ブラウザが scroll max に clamp する場合あり)。
  //
  // また、押下後フォーカスがボタンに残ると一部ブラウザが auto-scroll で
  // ボタンを viewport に入れに行くため、明示的に blur() してから scrollY
  // を復元することでこれも抑える。
  const olderToggleBtnRef = useRef<HTMLButtonElement | null>(null);
  const onToggleOlderPast = useCallback(() => {
    const beforeScrollY = window.scrollY;
    olderToggleBtnRef.current?.blur();
    setShowOlderPast((v) => !v);
    // React commit → ブラウザ paint 後に scrollY を復元。
    // rAF 1 回だと稀に layout 反映前の値で復元してしまう (ブラウザの
    // scroll-anchoring と競合) ため 2 段重ね。
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        if (window.scrollY !== beforeScrollY) {
          window.scrollTo({ top: beforeScrollY, behavior: "instant" });
        }
      });
    });
  }, []);

  const baseCardClass = "glass ";

  if (!result.ok) {
    return (
      <Card className={baseCardClass + "flex flex-col items-center gap-3 border-destructive/40 p-8 text-center"}>
        <span className="grid h-10 w-10 place-items-center rounded-md border border-destructive/40 bg-background/40 text-destructive">
          <AlertTriangle className="h-4 w-4" aria-hidden />
        </span>
        <p className="font-display text-foreground text-sm">スケジュール取得失敗</p>
        <p className="text-xs text-muted-foreground">
          {result.reason === "no-url"
            ? "NEXT_PUBLIC_SCHEDULE_URL が設定されていません。"
            : result.reason === "fetch-failed"
              ? "スケジュールサイトに接続できませんでした。"
              : "ページ構造の解析に失敗しました。"}
        </p>
      </Card>
    );
  }

  const { users, sessions, comments } = result.data;
  const commentsByAuthor = groupCommentsByAuthor(comments);
  // TODO #2 phase 2-B: native mode 専用メタ。sync mode では undefined のまま、
  // 各 SessionRow の `nativeSessionId` は undefined で既存 sync 経路をそのまま流す。
  const nativeMeta = result.data.nativeMeta;
  const attendanceOptionsForNative = result.data.attendanceOptions;
  const resolveNativeSessionId = (rawDate: string): string | undefined =>
    nativeMeta?.sessionIdByRawDate[rawDate];
  // 2.1 (2026-05-12): session-time-edit-popover が「override 有無 + default」を出すための
  // メタデータ resolver。native_schedule_sessions.start_time/end_time が NULL = default
  // 追従、NOT NULL = 日個別 override。
  const resolveNativeTimeMeta = (rawDate: string) => {
    if (!nativeMeta) return undefined;
    const o = nativeMeta.timeOverridesByRawDate[rawDate];
    return {
      overrideStart: o?.start ?? null,
      overrideEnd: o?.end ?? null,
      defaultStartTime: nativeMeta.defaultStartTime,
      defaultEndTime: nativeMeta.defaultEndTime,
    };
  };
  // 2.8 (2026-06-10) TODO #81 follow-up: placeholder 自動生成判定 + note 編集 popover
  // 初期値の resolver。両者とも sync mode では undefined → SessionRow 内で chip 非 mount /
  // note Textarea fallback "" になる。
  const resolveAutoGenerated = (rawDate: string): boolean =>
    nativeMeta?.autoGeneratedByRawDate[rawDate] ?? false;
  const resolveNativeNote = (rawDate: string): string | null =>
    nativeMeta?.noteByRawDate[rawDate] ?? null;

  const { upcoming, past } = splitSessions(sessions, limit);
  // Past sessions newest-first (already sorted by splitSessions). The
  // most-recent past sits at the top of the detail table — reads as
  // "what happened most recently" first.
  const renderedPast = showDetailedPast ? past : [];
  // 2.1 (2026-04-29): split into "recent" (≤ 60 days ago) and "older"
  // for the fold UX. cutoff は描画時点の Date.now なので、ページが
  // 長時間開きっぱなしでも問題なし (再 render で更新される)。
  const PAST_FOLD_THRESHOLD_MS = 60 * 24 * 60 * 60 * 1000;
  const pastCutoffMs = Date.now() - PAST_FOLD_THRESHOLD_MS;
  const recentPast = renderedPast.filter(
    (s) => s.date.getTime() >= pastCutoffMs,
  );
  const olderPast = renderedPast.filter(
    (s) => s.date.getTime() < pastCutoffMs,
  );

  // 日程セルは memo / 動画 / Logs の 3 アイコン枠を「行間で縦に揃える」ため
  // 1.9.27 から全行で確保していたが、どの行も使っていない表では ~68px が
  // そのまま死んだ余白になり、日付と確定列の間が大きく空いて見えていた。
  // 表単位で「1 行でも使っているか」を数えて、使っていない枠は確保しない
  // (使っている表では従来どおり縦に揃う)。
  const reserveSlotsFor = (list: ScheduleSession[]) => {
    let video = false;
    let logs = false;
    let memo = false;
    for (const s of list) {
      if (!video && lookupVideoLinks(s, sessionVideoLinks).length > 0) video = true;
      if (!logs && (sessionLogsByDate?.[s.rawDate]?.length ?? 0) > 0) logs = true;
      if (!memo && (memosByDate[s.rawDate]?.length ?? 0) > 0) memo = true;
      if (video && logs && memo) break;
    }
    // 動画リンクは自身の logsUrl も Logs 候補になるため、動画がある表では
    // Logs 枠も確保しておく (行ごとに片方だけ出ると横位置がずれる)。
    return { video, logs: logs || video, memo };
  };
  const upcomingSlots = reserveSlotsFor(upcoming);
  const pastSlots = reserveSlotsFor(renderedPast);

  if (upcoming.length === 0 && renderedPast.length === 0) {
    return (
      <EmptyState
        tone="neutral"
        icon={CalendarX2}
        title="予定なし"
        description="表示できる予定が見つかりませんでした。"
      />
    );
  }

  // Header row factory. The past table omits the "確定" column since
  // every past session was de facto held — the column only carries
  // signal for upcoming dates that may still slip. 確定 column has
  // 0 horizontal padding so the 16px badge sits flush against the
  // adjacent columns. Users get a min-width so name length doesn't
  // shift the table layout between rows / between the upcoming and
  // past tables.
  // 過去詳細表ではユーザー名横のメモアイコン (CommentPopover) を出さない
  // — 過去日のヘッダーで毎回メモが目に入って情報過多になっていたのを
  // 解消する (ユーザー要望)。upcoming は引き続きメモを出す。
  // TODO #50: past 詳細表 (showDecided=false) ではユーザ名のクリックで
  // 開く編集ページへの遷移を抑止 — 過去日付の出欠をうっかり編集して
  // しまう事故を防ぐ。upcoming 表は引き続き clickable のまま。
  const tableHead = (showDecided: boolean, showComments = true) => (
    <thead>
      <tr className="border-b border-border/60 text-[10px] font-medium tracking-normal text-muted-foreground">
        {/* 日程列はメンバー数が増えて横スクロールに入っても左端に固定する
            (`.sticky-col`, globals.css — sm 以上でのみ固定)。thead は行 tint が
            ないので疑似要素のオーバーレイは不要。 */}
        <th scope="col" className="sticky-col pl-3 pr-1 py-2">
          日程
        </th>
        {showDecided && (
          <th scope="col" className="px-1 py-2 text-center">
            確定
          </th>
        )}
        {users.map((u) => (
          <UserHeaderCell
            key={u.userId}
            user={u}
            comments={
              showComments ? (commentsByAuthor.get(u.name) ?? []) : []
            }
            editUrl={buildEditUrl(scheduleUrl, u.userId)}
            onOpenEditFrame={openEditFrame}
            clickable={showDecided}
            mode={mode}
            isOwnUser={
              mode === "native" && !!currentDiscordId && u.userId === currentDiscordId
            }
          />
        ))}
      </tr>
    </thead>
  );

  return (
    <div className="flex flex-col gap-4">
      {/* Upcoming sessions — primary card. Layout untouched. */}
      <Card className={baseCardClass + "overflow-hidden p-0"}>
        <Legend
          hasUltimateClear={hasUltimateClear}
          onRefresh={refreshSchedule}
          refreshing={refreshing}
          /* オリジナル (元サイトから取り込み) */
          topTextScraped={result.data.topText ?? null}
          /* 編集後 (Supabase app_settings.schedule_top_text_override)。
             同期で上書きされないので、運用ルールを portal 側で
             カスタマイズしてもそのまま残る。 */
          topTextOverride={topTextOverride}
          attendanceChoices={result.data.attendanceOptions.choices}
          isAdmin={isAdmin}
        />
        <div className="overflow-x-auto">
          <table className="w-full min-w-[640px] border-collapse text-left text-sm">
            {tableHead(true)}
            <tbody>
              {upcoming.map((s) => {
                const nativeSessionId = resolveNativeSessionId(s.rawDate);
                return (
                  <SessionRow
                    key={s.rawDate}
                    session={s}
                    users={users}
                    holidays={holidays}
                    videoLinks={lookupVideoLinks(s, sessionVideoLinks)}
                    sessionLogs={sessionLogsByDate?.[s.rawDate] ?? EMPTY_SESSION_LOGS}
                    scheduleUrl={scheduleUrl}
                    onOpenEditFrame={openEditFrame}
                    memos={memosByDate[s.rawDate] ?? EMPTY_MEMOS}
                    onRefreshMemos={refetchMemos}
                    mode={mode}
                    currentDiscordId={currentDiscordId}
                    isAdmin={isAdmin}
                    nativeSessionId={nativeSessionId}
                    attendanceOptions={attendanceOptionsForNative}
                    nativeTimeMeta={resolveNativeTimeMeta(s.rawDate)}
                    isAutoGenerated={resolveAutoGenerated(s.rawDate)}
                    nativeNote={resolveNativeNote(s.rawDate)}
                    slots={upcomingSlots}
                  />
                );
              })}
              {upcoming.length === 0 && (
                <tr>
                  <td
                    colSpan={2 + users.length}
                    className="px-3 py-6 text-center text-xs text-muted-foreground"
                  >
                    今後の予定はありません
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>

      {/* インライン編集ダイアログ — ユーザー名 / 出欠セルをタップすると
          ここがマウントされ、character-sheets の編集 URL を iframe で
          表示します。閉じるとスクロール位置などポータル側の状態は維持。 */}
      <ScheduleEditFrameDialog
        url={editTarget?.url ?? null}
        title={editTarget?.title ?? ""}
        targetRowIndex={editTarget?.targetRowIndex ?? null}
        onClose={() => setEditTarget(null)}
      />

      {/* Past sessions — separate card so the visual break is unmistakable.
          Hidden until the user enables the detail toggle. The "確定"
          column is dropped here since past sessions were all held.
          Manual snapshot trigger lives in the settings dialog now.
          2.1 (2026-04-29): 2 ヶ月以上前の行はデフォルト畳み、ボタンで
          展開できる UX に変更。直近 2 ヶ月の行は常時表示。 */}
      {showDetailedPast && renderedPast.length > 0 && (
        <Card className={baseCardClass + "overflow-hidden p-0"}>
          <header className="flex items-center justify-between gap-2 border-b border-border/40 bg-secondary/20 px-3 py-2">
            <div className="flex items-center gap-2 font-mono text-[10px] tracking-[0.22em] text-muted-foreground uppercase">
              <span className="inline-flex h-1.5 w-1.5 rounded-full bg-muted-foreground/60" />
              Past
              <span className="font-sans text-[11px] tracking-normal normal-case text-muted-foreground/85">
                · 詳細ログ (出欠表)
              </span>
            </div>
            <span className="text-[11px] tabular-nums text-muted-foreground">
              {showOlderPast || olderPast.length === 0
                ? `${renderedPast.length} 件`
                : `直近 ${recentPast.length} 件 / 全 ${renderedPast.length} 件`}
            </span>
          </header>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[640px] border-collapse text-left text-sm">
              {tableHead(false, false)}
              <tbody>
                {recentPast.map((s) => {
                  const nativeSessionId = resolveNativeSessionId(s.rawDate);
                  return (
                    <SessionRow
                      key={s.rawDate}
                      session={s}
                      users={users}
                      isPast
                      holidays={holidays}
                      showDecided={false}
                      videoLinks={lookupVideoLinks(s, sessionVideoLinks)}
                      sessionLogs={sessionLogsByDate?.[s.rawDate] ?? EMPTY_SESSION_LOGS}
                      scheduleUrl={scheduleUrl}
                      onOpenEditFrame={openEditFrame}
                      memos={memosByDate[s.rawDate] ?? EMPTY_MEMOS}
                      onRefreshMemos={refetchMemos}
                      mode={mode}
                      currentDiscordId={currentDiscordId}
                      isAdmin={isAdmin}
                      nativeSessionId={nativeSessionId}
                      attendanceOptions={attendanceOptionsForNative}
                      isAutoGenerated={resolveAutoGenerated(s.rawDate)}
                      nativeNote={resolveNativeNote(s.rawDate)}
                      slots={pastSlots}
                    />
                  );
                })}
                {olderPast.length > 0 && showOlderPast &&
                  olderPast.map((s) => {
                    const nativeSessionId = resolveNativeSessionId(s.rawDate);
                    return (
                      <SessionRow
                        key={s.rawDate}
                        session={s}
                        users={users}
                        isPast
                        holidays={holidays}
                        showDecided={false}
                        videoLinks={lookupVideoLinks(s, sessionVideoLinks)}
                        sessionLogs={sessionLogsByDate?.[s.rawDate] ?? EMPTY_SESSION_LOGS}
                        scheduleUrl={scheduleUrl}
                        onOpenEditFrame={openEditFrame}
                        memos={memosByDate[s.rawDate] ?? EMPTY_MEMOS}
                        onRefreshMemos={refetchMemos}
                        mode={mode}
                        currentDiscordId={currentDiscordId}
                        isAdmin={isAdmin}
                        nativeSessionId={nativeSessionId}
                        attendanceOptions={attendanceOptionsForNative}
                        isAutoGenerated={resolveAutoGenerated(s.rawDate)}
                        nativeNote={resolveNativeNote(s.rawDate)}
                        slots={pastSlots}
                      />
                    );
                  })}
                {olderPast.length > 0 && (
                  <tr>
                    <td
                      colSpan={1 + users.length}
                      className="border-t border-border/40 bg-secondary/10 px-3 py-2 text-center"
                    >
                      <button
                        ref={olderToggleBtnRef}
                        type="button"
                        onClick={onToggleOlderPast}
                        className="inline-flex items-center gap-1.5 rounded-md border border-border/40 bg-background/30 px-3 py-1 text-[11px] tracking-normal text-muted-foreground transition-colors hover:border-[var(--neon-cyan)]/60 hover:text-foreground"
                        aria-expanded={showOlderPast}
                      >
                        {showOlderPast ? (
                          <>
                            <ChevronUp className="h-3 w-3" aria-hidden />
                            2 ヶ月以上前を畳む
                          </>
                        ) : (
                          <>
                            <ChevronDown className="h-3 w-3" aria-hidden />
                            2 ヶ月以上前を表示 ({olderPast.length} 件)
                          </>
                        )}
                      </button>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </Card>
      )}
    </div>
  );
}

function UserHeaderCell({
  user,
  comments,
  editUrl,
  onOpenEditFrame,
  clickable = true,
  mode = "sync",
  isOwnUser = false,
}: {
  user: ScheduleUser;
  comments: ScheduleComment[];
  editUrl: string | null;
  /** Open the in-portal iframe dialog for the given URL. */
  onOpenEditFrame: (
    url: string,
    title: string,
    targetRowIndex?: number | null,
  ) => void;
  /**
   * TODO #50 (2.1, 2026-04-30): false で username を span 描画にし、
   * 編集ページへの遷移を抑止。past 詳細表のヘッダーで使う想定 — 過去日付
   * をうっかり編集してしまう事故を防ぐ。
   */
  clickable?: boolean;
  /**
   * 2.1 (2026-05-12) PR3-D: スケジュールソースモード。native では member
   * 全体コメント popover を本人のみマウント、他人 cell にはコメントを
   * tooltip / 折返し span で read-only 表示する。
   */
  mode?: ScheduleSourceMode;
  /**
   * 2.1 (2026-05-12) PR3-D: 本人 cell 判定 (mode === "native" && currentDiscordId
   * === user.userId)。true のとき MessageSquare icon を表示し popover を開ける。
   */
  isOwnUser?: boolean;
}) {
  const hasComments = comments.length > 0;
  const nativeComment =
    mode === "native" && user.comment && user.comment.trim()
      ? user.comment.trim()
      : null;
  // 2.1 (2026-05-12) PR3-D follow-up #2: native では本人 cell に常時 trigger
  // (空でも編集可) + 他人 cell でも comment ありなら trigger を出して hover/
  // click で popover 表示。名前 cell click でも popover を開けるよう、上位で
  // open state を持って NativeMemberCommentPopover に controlled prop で注入する。
  const nativeCommentTarget =
    mode === "native" && (isOwnUser || !!nativeComment);
  const [nativeCommentOpen, setNativeCommentOpen] = useState(false);

  // Username is a clickable button that opens the in-portal iframe
  // dialog (1.9.13). Comments live in a separate small button →
  // Popover. This works on both touch (tap) and mouse (click).
  //
  // Cap the inline width at 7rem and let CSS truncate with ellipsis when a
  // name is unusually long — prevents one outlier name from blowing out
  // the whole table's layout. The full name is still in the title
  // attribute (tooltip).
  // 非 clickable のときは underline / hover を消して「リンク風」の見た目を
  // 落とす — 押せそうに見えてしまうのを避ける。
  const nameClass = clickable
    ? "inline-block max-w-[7rem] truncate align-bottom underline decoration-dotted decoration-[var(--neon-cyan)]/60 underline-offset-4 transition-colors hover:decoration-[var(--neon-cyan)] hover:text-[var(--neon-cyan)]"
    : "inline-block max-w-[7rem] truncate align-bottom";

  // 2.1 (2026-05-12) PR3-D follow-up #2: native では名前 click も popover open
  // のトリガーにする (要望「名前・アイコンクリックでも開くようにして欲しい」)。
  // sync 経路では従来通り character-sheets 編集 iframe を開く。
  const nameNode = nativeCommentTarget ? (
    <button
      type="button"
      onClick={() => setNativeCommentOpen(true)}
      className={
        "inline-block max-w-[7rem] truncate align-bottom underline decoration-dotted decoration-[var(--neon-cyan)]/60 underline-offset-4 transition-colors hover:decoration-[var(--neon-cyan)] hover:text-[var(--neon-cyan)]"
      }
      title={
        isOwnUser
          ? `${user.name} のコメントを編集`
          : `${user.name} のコメントを表示`
      }
    >
      {user.name}
    </button>
  ) : clickable && editUrl ? (
    <button
      type="button"
      onClick={() => onOpenEditFrame(editUrl, `${user.name} の出欠を編集`)}
      className={nameClass}
      title={`${user.name} の出欠をその場で編集`}
    >
      {user.name}
    </button>
  ) : (
    <span className={nameClass} title={user.name}>
      {user.name}
    </span>
  );

  return (
    <th
      scope="col"
      // 1.9.29: px-2 → px-1.5 to bring the first member column closer
      // to the 日程 column. min-w-[5rem] still stabilizes per-column
      // width; max-w on the name (above) caps long names so they
      // ellipsize instead of pushing other columns offscreen.
      className="min-w-[5rem] px-1.5 py-2 text-center font-mono whitespace-nowrap"
    >
      <span className="inline-flex items-center gap-1">
        {nameNode}
        {hasComments && <CommentPopover user={user} comments={comments} />}
        {nativeCommentTarget ? (
          <NativeMemberCommentPopover
            currentComment={user.comment ?? null}
            userName={user.name}
            isOwn={isOwnUser}
            open={nativeCommentOpen}
            onOpenChange={setNativeCommentOpen}
          />
        ) : null}
      </span>
    </th>
  );
}

/**
 * Date cell label — plain colored span, no link. Video / Logs links
 * are rendered separately AFTER the time inside the row so both
 * icons sit at the end of the cell where the eye expects "actions".
 */
function DateLabel({
  text,
  holiday,
  decided,
  holidayName,
}: {
  text: string;
  holiday: boolean;
  decided: boolean;
  holidayName: string | null;
}) {
  const colorClass = holiday
    ? "font-bold text-rose-400 drop-shadow-[0_0_4px_color-mix(in_oklch,oklch(0.65_0.22_25)_40%,transparent)]"
    : decided
      ? "font-bold text-[var(--neon-cyan)] drop-shadow-[0_0_4px_color-mix(in_oklch,var(--neon-cyan)_40%,transparent)]"
      : "";
  return (
    <span className={colorClass} title={holidayName ?? undefined}>
      {text}
    </span>
  );
}

// SessionActionIcons / renderSingleVideoLink は C-5 で
// `@/components/portal/schedule/session-action-icons` に移動。

function SessionRow({
  session,
  users,
  isPast = false,
  holidays,
  showDecided = true,
  videoLinks = EMPTY_VIDEO_LINKS,
  sessionLogs = EMPTY_SESSION_LOGS,
  scheduleUrl,
  onOpenEditFrame,
  memos,
  onRefreshMemos,
  mode = "sync",
  currentDiscordId = null,
  isAdmin = false,
  nativeSessionId,
  attendanceOptions,
  nativeTimeMeta,
  isAutoGenerated = false,
  nativeNote = null,
  slots = DEFAULT_ROW_SLOTS,
}: {
  session: ScheduleSession;
  users: ScheduleUser[];
  isPast?: boolean;
  holidays?: JapaneseHolidaysMap;
  /** When false, drop the 確定 column entirely (past table). */
  showDecided?: boolean;
  /**
   * 同日紐付動画 (TODO #1)。0 件 = 紐付なし、1 件 = 単一リンク表示、
   * 2 件以上 = Film アイコンを DropdownMenu にして選択式にする。
   */
  videoLinks?: SessionVideoLink[];
  /**
   * FFLogs URL entries stored in `schedule_past_session_logs` for this
   * date. Used as a fallback Logs icon source when no matching video
   * exists, and as the editable list inside the memo popover.
   * TODO #64 (2.1, 2026-05-02 part5): array form.
   */
  sessionLogs?: SessionLogEntry[];
  /**
   * Source schedule URL — used to derive each user's character-sheets
   * input page so attendance cells can become "click here to edit"
   * targets.
   */
  scheduleUrl?: string | null;
  /** Open the in-portal iframe dialog for the given URL. */
  onOpenEditFrame: (
    url: string,
    title: string,
    targetRowIndex?: number | null,
  ) => void;
  /** 親が `useRealtimeAllScheduleMemos` で集約した live slice (TODO #11 phase 7)。 */
  memos: import("@/lib/schedule-memos-client").ScheduleSessionMemo[];
  /** Server-action 後の保険 refetch (旧 useRealtimeScheduleMemos の refetch 互換)。 */
  onRefreshMemos: () => Promise<void>;
  /** TODO #2 phase 2-B: スケジュールソースモード。default = "sync"。 */
  mode?: ScheduleSourceMode;
  /** TODO #2 phase 2-B: 認証済 Discord メンバーの ID。本人 cell 判定で使用。 */
  currentDiscordId?: string | null;
  /** TODO #2 phase 2-B: admin role 持ち。確定列の status toggle 表示判定。 */
  isAdmin?: boolean;
  /**
   * TODO #2 phase 2-B: native_schedule_sessions.id (uuid)。`nativeMeta` が
   * 解決した時のみセット。undefined のときは sync 経路を流す (status toggle / popover 非 mount)。
   */
  nativeSessionId?: string;
  /** TODO #2 phase 2-B: 凡例マスター (popover の symbol radio 用)。 */
  attendanceOptions?: ScheduleAttendanceOptions;
  /**
   * 2.1 (2026-05-12): native mode の admin が日個別時刻を編集するための meta。
   * undefined = sync mode or native meta 未解決。time edit popover の trigger 表示判定に使う。
   */
  nativeTimeMeta?: {
    overrideStart: string | null;
    overrideEnd: string | null;
    defaultStartTime: string;
    defaultEndTime: string;
  };
  /**
   * 2.8 (2026-06-10) TODO #81 follow-up: placeholder auto-insert された row
   * (`created_by_id IS NULL`) かどうか。true のとき時刻表示の直後に
   * `<AutoGeneratedBadge>` を mount。admin / 非 admin / past / 未来の全行で表示。
   */
  isAutoGenerated?: boolean;
  /**
   * 2.8 (2026-06-10) TODO #81 follow-up: native session の note 列 (空 / 未設定は null)。
   * SessionTimeEditPopover の Textarea 初期値に drill。
   */
  nativeNote?: string | null;
  /**
   * 日程セルのアイコン枠を確保するか (表単位で算出、`reserveSlotsFor`)。
   * 使っていない枠を確保しないことで日付〜確定列の余白を詰める。
   */
  slots?: { video: boolean; logs: boolean; memo: boolean };
}) {
  const decided = session.status === "DECISION";
  // Ref so the (separately-rendered) memo dot can open the popover.
  const popoverRef = useRef<SessionMemoPopoverHandle>(null);
  // Japanese national holidays get a red date label — overrides the
  // default and DECISION-cyan styling. Doesn't change the row background
  // so the past/decided treatment still composes underneath.
  const holiday = isJapaneseHoliday(session.date, holidays);
  const holidayName = holiday
    ? getJapaneseHolidayName(session.date, holidays)
    : null;
  return (
    <tr
      className={
        // group/row: 日程列は sticky で不透明背景を持つため、行の hover tint が
        // 届かない。固定セル側で group-hover/row: を使って tint を載せ直す。
        "group/row border-b border-border/30 transition-colors last:border-b-0 " +
        (isPast
          ? "" // past rows render at full opacity with no hover effect — once the past view is open, dimming-then-revealing on hover is just visual noise
          : decided
            ? "bg-[var(--neon-cyan)]/10 hover:bg-[var(--neon-cyan)]/16"
            : "hover:bg-secondary/40")
      }
    >
      <th
        scope="row"
        // 1.9.29: tighten 日程 column right-padding (pr-2 → pr-1) and
        // internal gap (gap-1.5 → gap-1). Cell auto-sizes to widest
        // row content; with both tables sharing identical icon slot
        // reservations the auto-size is consistent across them, so
        // the explicit `min-w-[15rem]` is no longer needed.
        //
        // `.sticky-col` (globals.css) で横スクロール時も左端に固定 (sm 以上)。
        // tr の背景 tint は固定列の不透明背景に隠れるので、同じ tint を
        // before: オーバーレイで再現する (past は tint も hover も無いので
        // 素のまま)。tint も `sm:` で揃える — 固定していないスマホ幅では tr の
        // 背景が普通に見えるため、載せると tint が二重になる。
        className={
          "sticky-col pl-3 pr-2 py-2 align-middle font-mono text-[12px] tabular-nums whitespace-nowrap text-foreground " +
          "before:pointer-events-none before:absolute before:inset-0 before:-z-10 before:content-[''] before:transition-colors " +
          (isPast
            ? ""
            : decided
              ? "sm:before:bg-[var(--neon-cyan)]/10 sm:group-hover/row:before:bg-[var(--neon-cyan)]/16"
              : "sm:group-hover/row:before:bg-secondary/40")
        }
      >
        <div className="flex items-center gap-1">
          {/* Date label color priority:
                1. Holiday → red glow
                2. DECISION → cyan glow + bold
                3. default → foreground
              Wrapped in a memo popover so any user can leave shared
              notes for this session by clicking the date. */}
          <SessionMemoPopover
            ref={popoverRef}
            rawDate={session.rawDate}
            displayDate={session.rawDate.split(" ")[0] ?? session.rawDate}
            memos={memos}
            onRefresh={onRefreshMemos}
            sessionLogs={sessionLogs}
            sessionDetails={{
              parsedDate: session.date.toISOString(),
              startTime: session.startTime,
              endTime: session.endTime,
              dayOfWeek: session.dayOfWeek,
            }}
          >
            <DateLabel
              text={session.rawDate.split(" ")[0]!}
              holiday={holiday}
              decided={decided}
              holidayName={holidayName}
            />
          </SessionMemoPopover>
          {(session.startTime || session.endTime) && (
            <span className="font-mono text-[11px] tabular-nums text-muted-foreground/85">
              {session.startTime}
              <span className="mx-0.5 opacity-60">~</span>
              {session.endTime}
            </span>
          )}
          {/* 日付 / 時刻の右に続く chip + アイコン群。時刻と地続きに見えて
              「時刻に寄りすぎ」に見えるため、1 つの塊として ICON_GROUP_CLASS
              で時刻から離す (ユーザー指摘 2026-08-05)。 */}
          <span className={ICON_GROUP_CLASS}>
          {/* 2.8 (2026-06-10) TODO #81 follow-up: placeholder auto-insert 行
              (`created_by_id IS NULL`) には「auto」chip を表示。admin / 非 admin /
              past / 未来の全行で出す (placeholder と手動候補の区別は全員に有用)。
              sync mode では isAutoGenerated は常に false (nativeMeta undefined) で
              chip mount スキップ。 */}
          {mode === "native" && isAutoGenerated ? <AutoGeneratedBadge /> : null}
          {/* 2.1 (2026-05-12): native admin の未来日付に限って日個別時刻 edit popover の
              clock icon を表示。past 日付は時刻変更したくないので isPast を排除。
              2.8 (2026-06-10) TODO #81 follow-up: 同 popover に note Textarea が
              追加されているため nativeNote を drill。 */}
          {!isPast &&
            mode === "native" &&
            isAdmin &&
            nativeSessionId &&
            nativeTimeMeta ? (
            <SessionTimeEditPopover
              sessionId={nativeSessionId}
              overrideStart={nativeTimeMeta.overrideStart}
              overrideEnd={nativeTimeMeta.overrideEnd}
              defaultStartTime={nativeTimeMeta.defaultStartTime}
              defaultEndTime={nativeTimeMeta.defaultEndTime}
              displayDate={session.rawDate.split(" ")[0] ?? session.rawDate}
              note={nativeNote}
            />
          ) : null}
          {/* Memo indicator placed right after the time per user
              request — visible whether or not video/Logs links are
              also rendered for this row. `reserveSpace` keeps an
              invisible placeholder so memo / video / Logs icons sit
              at the same horizontal position across all rows
              (1.9.27). */}
          <SessionMemoDot
            count={memos.length}
            reserveSpace={slots.memo}
            onClick={() => popoverRef.current?.toggle()}
          />
          {/* Action icons — Film slot (left) | BarChart3 slot (right).
              1.9.27: ALWAYS reserve both slots in the detail table so
              icons share vertical column alignment across all rows.
              When a slot has no content, render an invisible h-5 w-5
              placeholder. */}
          <SessionActionIcons
            videoLinks={videoLinks}
            sessionLogs={sessionLogs}
            isPast={isPast}
            displayDate={session.rawDate.split(" ")[0] ?? session.rawDate}
            reserve={{ video: slots.video, logs: slots.logs }}
          />
          {/* 2.9 (2026-06-10) TODO #73 follow-up: native スケジュール版の
              FFLogs URL manual link 追加 / 削除 popover の trigger (`+` icon)。
              `mode === 'native' && isAdmin && status === 'DECISION' && nativeSessionId`
              の 4 条件 AND で mount。past / 未来問わず DECISION 行に出す
              (誤 auto-match の削除 / 後追い手動追加の両方に対応するため)。
              SessionActionIcons の Logs slot 隣に配置し、auto/manual の
              source 別 badge と並べて一括管理できるようにする。 */}
          {mode === "native" &&
            isAdmin &&
            session.status === "DECISION" &&
            nativeSessionId && (
              <NativeFflogsLinkPopover
                sessionId={nativeSessionId}
                displayDate={session.rawDate.split(" ")[0] ?? session.rawDate}
                sessionLogs={sessionLogs}
              />
            )}
          {/* 2.9 (2026-08-24): 過去ログの admin 専用ゴミ箱。実施しなかったのに
              取り消し忘れで記録された日を消すための導線 (詳細は
              `past-session-remove-button.tsx`)。過去行 (`isPast`) の admin に
              だけ出す — 未来 / 当日行は候補日の中止 (確定列の status toggle) で
              扱うので二重の導線を作らない。sync / native 両モードで表示し、
              消し方の分岐は Server Action 側に寄せている。 */}
          {isPast && isAdmin && (
            <PastSessionRemoveButton
              rawDate={session.rawDate}
              displayDate={session.rawDate.split(" ")[0] ?? session.rawDate}
              mode={mode}
              sessionDetails={{
                parsedDate: session.date.toISOString(),
                startTime: session.startTime,
                endTime: session.endTime,
                dayOfWeek: session.dayOfWeek,
              }}
            />
          )}
          </span>
        </div>
      </th>
      {showDecided && (
        <td className="px-1 py-2 text-center align-middle">
          {/* TODO #2 phase 2-B: native mode + admin の時は確定列の中身を
              SessionStatusToggle に置換し DropdownMenu で CANDIDATE / DECISION /
              CANCELLED を切替える。CANCELLED 選択は次回 fetch で行が消える。
              sync mode (`mode !== "native"`) や非 admin / nativeSessionId 解決
              失敗時は既存 IIFE 経路 (sync 互換の確定 badge / 未確定 dot) を流す。 */}
          {mode === "native" && isAdmin && nativeSessionId ? (
            <span className="inline-flex items-center justify-center">
              <SessionStatusToggle
                sessionId={nativeSessionId}
                currentStatus={session.status}
                displayDate={session.rawDate.split(" ")[0] ?? session.rawDate}
              />
              {session.status === "DECISION" && !isPast && (
                <SessionDiscordNotifyButton
                  sessionId={nativeSessionId}
                  displayDate={session.rawDate.split(" ")[0] ?? session.rawDate}
                />
              )}
            </span>
          ) : (() => {
            // TODO #44 (2.1, 2026-04-30): clicking the 確定 cell opens
            // the schedule list URL in the iframe dialog with a
            // `#row_N` fragment anchor so character-sheets natively
            // jumps to the matching date row. `session.rowIndex` is the
            // N from `<tr id="row_N">` (parsed from the source HTML).
            // `null` when the session is synthetic (Discord/snapshot
            // backed past row with no DOM anchor) — falls back to the
            // default `#comment` landing.
            //
            // 2.1 part9 (2026-04-30): 確定セル click は `/schedule/list`
            // (一覧ページ) を開くが、character-sheets `/list` 側は固定
            // header が anchor 行に被さって視覚的に「1 行下にジャンプ
            // した」ように見える ("日付+1 の行が画面最上端" になる)。
            // これを相殺するため確定セル経由のみ `rowIndex - 1` を渡す。
            // メンバー列 (出欠セル) は `/schedule/input` 側で問題なく
            // 該当行が画面に見えるので補正不要。
            //
            // 2.1 part10: rowIndex=0 (最古未来日 = 一覧の最上端行) は
            // `-1` 補正できないので sentinel `-1` を渡す。dialog 側で
            // hash 抜き URL に変換され、ブラウザ scroll=0 で開く →
            // 固定 header の直下に row_0 が見える状態になる。
            const targetRowIndex =
              typeof session.rowIndex === "number"
                ? session.rowIndex === 0
                  ? -1
                  : session.rowIndex - 1
                : null;
            const dateLabel =
              session.rawDate.split(" ")[0] ?? session.rawDate;
            const safeScheduleUrl = scheduleUrl ?? null;
            const openTarget = () => {
              if (!safeScheduleUrl) return;
              onOpenEditFrame(
                safeScheduleUrl,
                `スケジュール (${dateLabel} の行へ移動)`,
                targetRowIndex,
              );
            };
            const sharedClass =
              "inline-flex h-6 items-center justify-center rounded-md transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--neon-cyan)]/60 active:translate-y-px";

            if (decided) {
              const badge = (
                <span
                  aria-label="日程確定"
                  title={
                    safeScheduleUrl
                      ? `日程確定 — クリックで ${dateLabel} の行までスクロール`
                      : "日程確定"
                  }
                  className={DECISION_BADGE_CLASS}
                >
                  確定
                </span>
              );
              return safeScheduleUrl ? (
                <button
                  type="button"
                  onClick={openTarget}
                  className={`${sharedClass} hover:scale-105`}
                  aria-label={`スケジュール元サイトの ${dateLabel} の行を開く`}
                >
                  {badge}
                </button>
              ) : (
                badge
              );
            }
            // 未確定 (·): クリックで同じく該当日にスクロール
            return safeScheduleUrl ? (
              <button
                type="button"
                onClick={openTarget}
                title={`未確定 — クリックで ${dateLabel} の行までスクロール`}
                aria-label={`スケジュール元サイトの ${dateLabel} の行を開く`}
                className={`${sharedClass} px-2 text-muted-foreground/40 hover:bg-secondary/40 hover:text-foreground/80`}
              >
                ·
              </button>
            ) : (
              <span
                aria-hidden
                title="未確定"
                className="inline-flex h-6 items-center justify-center text-muted-foreground/40"
              >
                ·
              </span>
            );
          })()}
        </td>
      )}
      {users.map((u) => {
        const att = session.attendances[u.userId] ?? "－";
        const editUrl = buildEditUrl(scheduleUrl, u.userId);
        const dateLabel = session.rawDate.split(" ")[0] ?? session.rawDate;
        const tone = ATT_TONE[att] ?? ATT_TONE_FALLBACK;
        // 2026-09-06 (W-13): 遅刻 / 早退の予定時刻 (native のみ)。記号の
        // 横に `21:30〜` を 9px で添える。無い人のセルは従来どおり。
        const times = session.attendanceTimes?.[u.userId] ?? null;
        const timesHint = formatAttendanceTimesHint(times);
        const timesTitle = describeAttendanceTimes(times);
        // TODO #2 phase 2-B: native mode + 本人行 + nativeSessionId 解決済 +
        // 出欠選択肢取得済 + 過去日でない、の 5 条件 AND で popover trigger 化。
        // 過去日 (`isPast`) は sync 経路と揃えて編集不可 (記録閲覧のみ)。
        const enableNativePopover =
          mode === "native" &&
          !isPast &&
          currentDiscordId === u.userId &&
          Boolean(nativeSessionId) &&
          Boolean(attendanceOptions);
        if (enableNativePopover && nativeSessionId && attendanceOptions) {
          return (
            <td key={u.userId} className="px-1.5 py-2 align-middle text-center">
              <NativeAttendancePopover
                sessionId={nativeSessionId}
                currentSymbol={att}
                attendanceOptions={attendanceOptions}
                triggerClass={tone}
                userName={u.name}
                displayDate={dateLabel}
                currentTimes={times}
              />
            </td>
          );
        }
        const symbol = (
          <span
            // Drop `font-mono` for the symbols — ◯ ⏰ △ × － are CJK
            // full-width / emoji glyphs that fall back to system fonts
            // when JetBrains Mono lacks them. The fallback's vertical
            // metrics differ slightly per glyph (especially ⏰ which
            // sits taller in the line-box), causing perceived
            // misalignment. Using the default sans + `leading-none`
            // forces every cell to render the glyph at the same
            // baseline within a fixed h-5 box.
            className={
              // max-w + truncate: 記号は設定画面で自由編集できるため、長い値で
              // h-5 のセル高が壊れないよう抑える。予定時刻付きは少し広げる。
              "inline-flex h-5 min-w-[1.75rem] items-center justify-center truncate rounded-sm border px-1 text-[12px] whitespace-nowrap leading-none transition-transform " +
              (timesHint ? "max-w-[7rem] " : "max-w-[5rem] ") +
              tone
            }
            aria-label={`${u.name}: ${att}` + (timesTitle ? ` (${timesTitle})` : "")}
            title={timesTitle ?? undefined}
          >
            {att}
            {timesHint && (
              <span className="ml-1 font-mono text-[9px] leading-none opacity-80 tabular-nums">
                {timesHint}
              </span>
            )}
          </span>
        );
        // 過去日程の出欠セルは button にしない (ユーザー要望 2026-04-29 v2):
        // 過去の `－` 等を誤クリックすると character-sheets の編集 iframe
        // が開いて遷移してしまうため、past 行は記録としての表示のみに固定。
        // 編集 (= upcoming 全日程の入力) はユーザー名ヘッダーと upcoming
        // 行の出欠セルから引き続きアクセス可能。
        const clickable = Boolean(editUrl) && !isPast;
        return (
          <td key={u.userId} className="px-1.5 py-2 align-middle text-center">
            {clickable && editUrl ? (
              // ボタン化 (1.9.13): その場でインライン iframe ダイアログを
              // 開いて出欠を編集。タブ移動なしで戻れる。hover の scale +
              // focus ring で「タップ可能」のフィードバックを残す。
              // 2.1+ (TODO #44 v3): 該当行へは `#row_N` hash anchor で
              // ジャンプ。session.rowIndex は parser が `<tr id="row_N">`
              // から抜き出した N (synthetic 行は null = 通常 mode の
              // `#comment` 着地になる)。
              <button
                type="button"
                onClick={() =>
                  onOpenEditFrame(
                    editUrl,
                    `${u.name} の出欠を編集 (${dateLabel} を含む)`,
                    session.rowIndex,
                  )
                }
                title={`${u.name} の出欠をその場で編集 (${dateLabel} を含む全日程)`}
                className="group/cell inline-flex rounded-sm transition-transform hover:scale-110 focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--neon-cyan)]/60 active:scale-95"
              >
                {symbol}
              </button>
            ) : (
              symbol
            )}
          </td>
        );
      })}
    </tr>
  );
}

// Legend は C-5 で `@/components/portal/schedule/legend` に移動。

// groupCommentsByAuthor / splitSessions は C-5 で `@/lib/schedule/session-utils`
// に移動。
