/**
 * 2.8 (2026-06-10) TODO #81 follow-up: placeholder auto-insert された
 * native_schedule_sessions row (`created_by_id IS NULL`) を視覚的に区別する
 * 小型 chip。schedule-list.tsx の SessionRow で時刻表示の直後に mount され、
 * admin / 非 admin の両方に表示 (placeholder と admin 手動追加の区別は
 * 全員に有用 — 誤って「DECISION 化済」と勘違いするのを防ぐ意味もある)。
 *
 * `created_by_id IS NULL` を auto シグナルとして使う根拠:
 * - `ensureNativeMonthlyPlaceholders()` (server util) は service_role client で
 *   `created_by_id` を指定せず INSERT (= NULL) する
 * - `createNativeScheduleSessionAction()` (admin の CandidateDateDialog 経由) は
 *   `auth.user.discordId` を明示 INSERT する
 *
 * style は SessionTimeEditPopover の neon-cyan tinted border (override 表示)
 * を踏襲しつつ、より控えめな muted-foreground 色で「auto = 自動」の補助情報
 * であることを示す。
 */
export function AutoGeneratedBadge() {
  return (
    <span
      aria-label="placeholder (admin が時刻 / 確定状態を編集可)"
      title="placeholder (admin が時刻 / 確定状態を編集可)"
      className="inline-flex items-center rounded-sm border border-border/40 bg-background/30 px-1 py-[0.5px] font-mono text-[8.5px] leading-none tracking-[0.18em] text-muted-foreground/80 uppercase"
    >
      auto
    </span>
  );
}
