"use client";

import { type FrameDeviation } from "@/lib/schedule/recurring-frames";
import { useMessages } from "@/lib/i18n/client";

/**
 * 定期枠からの「例外」バッジ (W-15、2026-09-08)。
 *
 * 調査ノート第 4 回 7-B W-15 のデメリット欄は **「例外 UI が無いと定期化は
 * 逆効果」**。定期枠を決めた瞬間に「いつもどおり」が既定になるので、
 * いつもどおりでない日が**見て分かる**必要がある。
 *
 * 出すのは 2 種類:
 *   - `extra` = **臨時**: 定期枠に無い曜日の枠 (「今週だけ日曜も」)
 *   - `time`  = **今回だけ**: 定期枠の曜日だが時刻を変えている
 *
 * 「今週スキップ」は 3 つ目の例外だが、その行は status = CANCELLED になって
 * 一覧から消えるためここでは扱わない (取り消した日の一覧は設定画面の
 * 「中止した候補日」節にある)。
 *
 * 定期枠が未設定なら `frameDeviation()` が常に `none` を返すので、この
 * バッジは 1 つも出ない = 既存デプロイの見た目は変わらない。
 *
 * style は `AutoGeneratedBadge` と対にする (同じ列に並ぶ補助情報)。ただし
 * こちらは**人が意図して外した印**なので、muted ではなく琥珀寄りにして
 * 「いつもと違う」が拾えるようにしている。文字も併記するので、色だけに
 * 頼っていない (`globals.css` の色の方針)。
 */
export function FrameDeviationBadge({
  deviation,
}: {
  deviation: FrameDeviation;
}) {
  const m = useMessages();
  if (deviation === "none") return null;
  const label =
    deviation === "extra" ? m.frameBadge.extra : m.frameBadge.timeOverride;
  const title =
    deviation === "extra"
      ? m.frameBadge.extraTitle
      : m.frameBadge.timeOverrideTitle;
  return (
    <span
      aria-label={title}
      title={title}
      className="inline-flex items-center rounded-sm border border-amber-400/40 bg-amber-400/10 px-1 py-[0.5px] font-mono text-[11px] leading-none tracking-normal text-amber-200"
    >
      {label}
    </span>
  );
}
