"use client";

import dynamic from "next/dynamic";

/**
 * native スケジュール系コンポーネントの chunk 分離 re-export
 * (2026-07-12 監査 C-2)。
 *
 * schedule-list / schedule-page-body はこれらを静的 import していたため、
 * **sync モードの TOP でも** native 一式 (~1,700 行) が初期 client bundle
 * に混入していた。全 render 箇所が `mode === "native"` ガード下にあるため、
 * `next/dynamic` の条件 render 規則 (render されなければ chunk も fetch
 * されない) で sync モードから完全に外れる。native モードでも初期チャンク
 * とは並行の別 chunk になる。
 *
 * ⚠ `ssr: false` は付けない (デフォルト ssr: true のまま)。
 *   AutoGeneratedBadge / SessionStatusToggle / SessionTimeEditPopover の
 *   トリガー等は native モードで**常時表示**されるため、ssr:false にすると
 *   SSR HTML から欠落 → hydrate 後に pop-in し、todos/11.md の
 *   「常時表示トリガーの dynamic 化 (レイアウトシフト) 禁止」と同じ問題を
 *   踏む。ssr:true なら SSR HTML は従来と完全に同一で、client 側の
 *   ダウンロード単位だけが分かれる。
 */

export const NativeAttendancePopover = dynamic(() =>
  import("./native-attendance-popover").then((m) => ({
    default: m.NativeAttendancePopover,
  })),
);

export const SessionStatusToggle = dynamic(() =>
  import("./session-status-toggle").then((m) => ({
    default: m.SessionStatusToggle,
  })),
);

export const SessionDiscordNotifyButton = dynamic(() =>
  import("./session-discord-notify-button").then((m) => ({
    default: m.SessionDiscordNotifyButton,
  })),
);

export const SessionTimeEditPopover = dynamic(() =>
  import("./session-time-edit-popover").then((m) => ({
    default: m.SessionTimeEditPopover,
  })),
);

export const NativeMemberCommentPopover = dynamic(() =>
  import("./native-member-comment-popover").then((m) => ({
    default: m.NativeMemberCommentPopover,
  })),
);

export const AutoGeneratedBadge = dynamic(() =>
  import("./auto-generated-badge").then((m) => ({
    default: m.AutoGeneratedBadge,
  })),
);

export const NativeFflogsLinkPopover = dynamic(() =>
  import("./native-fflogs-link-popover").then((m) => ({
    default: m.NativeFflogsLinkPopover,
  })),
);

export const CandidateDateDialog = dynamic(() =>
  import("./candidate-date-dialog").then((m) => ({
    default: m.CandidateDateDialog,
  })),
);
